name: CD Production

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      code: read
      releases: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish latest image and stable release
        uses: ./.gitea/actions/publish
        with:
          image-tag: latest
          prerelease: 'false'
          registry-username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.GITEA_TOKEN }}
