name: Build Production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js v22.16.0 einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Build ausführen
        run: npm run buildDevelopment

      - name: Version aus package.json auslesen
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "VERSION=$version" >> $GITHUB_ENV
          
      - name: dist-Ordner umbenennen
        run: mv dist "${{ env.VERSION }}"

      - name: Version-Ordner zippen
        run: zip -r "${{ env.VERSION }}-DEV.zip" "${{ env.VERSION }}"

      - name: Build-Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: ${{ env.VERSION }}
