name: Build Validation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js v22.16.0 einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Build DEV ausführen
        run: npm run buildDevelopment

      - name: Build PROD ausführen
        run: npm run buildProduction
